// Command nz-locality-gen renders the LINZ locality names used by the parser.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type sourceDocument struct {
	Features []struct {
		Attributes struct {
			Name                string `json:"name"`
			AdditionalName      string `json:"additional_name"`
			NameASCII           string `json:"name_ascii"`
			AdditionalNameASCII string `json:"additional_name_ascii"`
			MajorName           string `json:"major_name"`
			MajorNameASCII      string `json:"major_name_ascii"`
		} `json:"attributes"`
	} `json:"features"`
}

func main() {
	source := flag.String("source", "", "LINZ ArcGIS query JSON snapshot")
	output := flag.String("output", "nz_localities_generated.go", "generated Go file")
	check := flag.String("check", "", "verify an existing generated Go file")
	flag.Parse()

	if *source == "" {
		fmt.Fprintln(os.Stderr, "-source is required")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*source)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read LINZ source: %v\n", err)
		os.Exit(1)
	}
	generated, err := render(raw)
	if err != nil {
		fmt.Fprintf(os.Stderr, "render LINZ localities: %v\n", err)
		os.Exit(1)
	}
	if *check != "" {
		existing, err := os.ReadFile(*check)
		if err != nil {
			fmt.Fprintf(os.Stderr, "read generated locality index: %v\n", err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, generated) {
			fmt.Fprintln(os.Stderr, "generated locality index does not match source")
			os.Exit(1)
		}
		return
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated locality index: %v\n", err)
		os.Exit(1)
	}
}

func render(raw []byte) ([]byte, error) {
	var source sourceDocument
	if err := json.Unmarshal(raw, &source); err != nil {
		return nil, fmt.Errorf("decode ArcGIS query response: %w", err)
	}

	names := make(map[string]struct{}, len(source.Features))
	for _, feature := range source.Features {
		for _, name := range []string{
			feature.Attributes.Name,
			feature.Attributes.AdditionalName,
			feature.Attributes.NameASCII,
			feature.Attributes.AdditionalNameASCII,
			feature.Attributes.MajorName,
			feature.Attributes.MajorNameASCII,
		} {
			name = strings.ToUpper(strings.TrimSpace(name))
			if name != "" {
				names[name] = struct{}{}
			}
		}
	}
	if len(names) == 0 {
		return nil, fmt.Errorf("source contains no locality names")
	}

	ordered := make([]string, 0, len(names))
	for name := range names {
		ordered = append(ordered, name)
	}
	sort.Strings(ordered)

	var output strings.Builder
	output.WriteString("// Code generated by cmd/nz-locality-gen; DO NOT EDIT.\n\n")
	output.WriteString("package anzaddress\n\n")
	fmt.Fprintf(&output, "const nzMaxLocalityTokens = %d\n\n", maxTokens(ordered))
	output.WriteString("var nzLocalities = map[string]struct{}{\n")
	for _, name := range ordered {
		fmt.Fprintf(&output, "\t%q: {},\n", name)
	}
	output.WriteString("}\n")

	formatted, err := format.Source([]byte(output.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated Go: %w", err)
	}
	return formatted, nil
}

func maxTokens(names []string) int {
	maximum := 1
	for _, name := range names {
		if tokens := len(strings.Fields(name)); tokens > maximum {
			maximum = tokens
		}
	}
	return maximum
}
