package main

import (
	"archive/zip"
	"bytes"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
)

func TestResolveLatestGNAFSelectsNewestGDA2020Zip(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(writer http.ResponseWriter, request *http.Request) {
		writer.Header().Set("Content-Type", "application/json")
		_, _ = writer.Write([]byte(`{
  "success": true,
  "result": {
    "resources": [
      {"name":"Release report August 2026","format":"PDF","last_modified":"2026-08-18T00:00:00Z","url":"https://example.test/report.pdf"},
      {"name":"AUG 2026 - Geoscape G-NAF - GDA94","format":"ZIP","last_modified":"2026-08-17T04:00:00Z","url":"https://example.test/gnaf-aug-2026-gda94.zip"},
      {"name":"FEB 2026 - Geoscape G-NAF - GDA2020","format":"ZIP","last_modified":"2026-02-16T03:00:00Z","url":"https://example.test/gnaf-feb-2026-gda2020.zip"},
      {"name":"AUG 2026 - Geoscape G-NAF - GDA2020","format":"ZIP","last_modified":"2026-08-17T03:00:00Z","url":"https://example.test/gnaf-aug-2026-gda2020.zip"}
    ]
  }
}`))
	}))
	defer server.Close()

	got, err := resolveLatestGNAF(server.Client(), server.URL)
	if err != nil {
		t.Fatalf("resolve latest G-NAF: %v", err)
	}
	const expected = "https://example.test/gnaf-aug-2026-gda2020.zip"
	if got != expected {
		t.Fatalf("expected %s, got %s", expected, got)
	}
}

func TestReadGNAFLocalitiesIncludesPrimaryAndAliasNames(t *testing.T) {
	var archive bytes.Buffer
	writer := zip.NewWriter(&archive)
	addZipFile(t, writer,
		"G-NAF/G-NAF AUGUST 2026/Standard/QLD_LOCALITY_psv.psv",
		"LOCALITY_PID|LOCALITY_NAME|STATE_PID\nloc1|BRISBANE|3\n",
	)
	addZipFile(t, writer,
		"G-NAF/G-NAF AUGUST 2026/Standard/ACT_LOCALITY_ALIAS_psv.psv",
		"LOCALITY_ALIAS_PID|LOCALITY_PID|NAME|STATE_PID\nalias1|loc2|CANBERRA|8\n",
	)
	if err := writer.Close(); err != nil {
		t.Fatalf("close zip writer: %v", err)
	}

	reader, err := zip.NewReader(bytes.NewReader(archive.Bytes()), int64(archive.Len()))
	if err != nil {
		t.Fatalf("open zip reader: %v", err)
	}
	localities, err := readGNAFLocalities(reader)
	if err != nil {
		t.Fatalf("read G-NAF localities: %v", err)
	}

	if got := localities["BRISBANE"]; got != stateBits["QLD"] {
		t.Errorf("BRISBANE state mask: expected %08b, got %08b", stateBits["QLD"], got)
	}
	if got := localities["CANBERRA"]; got != stateBits["ACT"] {
		t.Errorf("CANBERRA state mask: expected %08b, got %08b", stateBits["ACT"], got)
	}
}

func TestRenderLocalitiesIsDeterministicAndRecordsResolvedSource(t *testing.T) {
	localities := map[string]uint8{
		"RICHMOND": stateBits["VIC"] | stateBits["NSW"],
		"SYDNEY":   stateBits["NSW"],
	}
	const resolvedSource = "https://example.test/g-naf_feb27_allstates_gda2020_psv.zip"

	first, err := renderLocalities(localities, resolvedSource)
	if err != nil {
		t.Fatalf("render first locality index: %v", err)
	}
	second, err := renderLocalities(localities, resolvedSource)
	if err != nil {
		t.Fatalf("render second locality index: %v", err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("expected identical generated output for identical input")
	}
	if !strings.Contains(string(first), "// Source: "+resolvedSource+" (Geoscape G-NAF, GDA2020 PSV)") {
		t.Fatalf("expected resolved source provenance without a hard-coded edition:\n%s", first)
	}
}

func TestSourceFromGeneratedOutput(t *testing.T) {
	const expected = "https://example.test/g-naf_aug26_allstates_gda2020_psv.zip"
	generated := []byte("// Code generated by cmd/locality-gen; DO NOT EDIT.\n// Source: " + expected + " (Geoscape G-NAF, GDA2020 PSV)\n\npackage anzaddress\n")

	got, err := sourceFromGenerated(generated)
	if err != nil {
		t.Fatalf("read recorded source: %v", err)
	}
	if got != expected {
		t.Fatalf("expected %s, got %s", expected, got)
	}
}

func addZipFile(t *testing.T, writer *zip.Writer, name, contents string) {
	t.Helper()
	file, err := writer.Create(name)
	if err != nil {
		t.Fatalf("create zip file %s: %v", name, err)
	}
	if _, err := file.Write([]byte(contents)); err != nil {
		t.Fatalf("write zip file %s: %v", name, err)
	}
}
