package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"
	"time"
)

const (
	defaultEndpoint = "https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/SAL/MapServer/0/query"
	pageSize        = 2000
)

var stateBits = map[string]uint8{
	"1": 1 << 0, // NSW
	"2": 1 << 1, // VIC
	"3": 1 << 2, // QLD
	"4": 1 << 3, // SA
	"5": 1 << 4, // WA
	"6": 1 << 5, // TAS
	"8": 1 << 6, // ACT
	"7": 1 << 7, // NT
}

type queryResponse struct {
	Features []struct {
		Attributes struct {
			Name      string `json:"sal_name_2021"`
			StateCode string `json:"state_code_2021"`
		} `json:"attributes"`
	} `json:"features"`
	Error *struct {
		Code    int    `json:"code"`
		Message string `json:"message"`
	} `json:"error,omitempty"`
}

func main() {
	output := flag.String("output", "localities_generated.go", "generated Go file")
	endpoint := flag.String("endpoint", defaultEndpoint, "ABS SAL ArcGIS query endpoint")
	flag.Parse()

	localities, err := fetchLocalities(*endpoint)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	generated, err := renderLocalities(localities, *endpoint)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", *output, err)
		os.Exit(1)
	}
}

func fetchLocalities(endpoint string) (map[string]uint8, error) {
	client := &http.Client{Timeout: 30 * time.Second}
	localities := make(map[string]uint8, 15_000)

	for offset := 0; ; offset += pageSize {
		query, err := url.Parse(endpoint)
		if err != nil {
			return nil, fmt.Errorf("parse endpoint: %w", err)
		}
		values := query.Query()
		values.Set("where", "1=1")
		values.Set("outFields", "sal_name_2021,state_code_2021")
		values.Set("returnGeometry", "false")
		values.Set("orderByFields", "objectid")
		values.Set("resultOffset", fmt.Sprint(offset))
		values.Set("resultRecordCount", fmt.Sprint(pageSize))
		values.Set("f", "json")
		query.RawQuery = values.Encode()

		response, err := client.Get(query.String())
		if err != nil {
			return nil, fmt.Errorf("fetch locality page at offset %d: %w", offset, err)
		}

		var page queryResponse
		decodeErr := json.NewDecoder(response.Body).Decode(&page)
		closeErr := response.Body.Close()
		if response.StatusCode != http.StatusOK {
			return nil, fmt.Errorf("fetch locality page at offset %d: %s", offset, response.Status)
		}
		if decodeErr != nil {
			return nil, fmt.Errorf("decode locality page at offset %d: %w", offset, decodeErr)
		}
		if closeErr != nil {
			return nil, fmt.Errorf("close locality response at offset %d: %w", offset, closeErr)
		}
		if page.Error != nil {
			return nil, fmt.Errorf("ABS query error %d: %s", page.Error.Code, page.Error.Message)
		}

		for _, feature := range page.Features {
			bit, supported := stateBits[feature.Attributes.StateCode]
			if !supported {
				continue
			}
			name := normalizeLocalityName(feature.Attributes.Name)
			if name != "" {
				localities[name] |= bit
			}
		}

		if len(page.Features) < pageSize {
			break
		}
	}

	return localities, nil
}

func normalizeLocalityName(name string) string {
	name = strings.TrimSpace(name)
	if qualifier := strings.LastIndex(name, " ("); qualifier >= 0 && strings.HasSuffix(name, ")") {
		name = name[:qualifier]
	}
	return strings.ToUpper(strings.Join(strings.Fields(name), " "))
}

func renderLocalities(localities map[string]uint8, endpoint string) ([]byte, error) {
	names := make([]string, 0, len(localities))
	maxTokens := 0
	for name := range localities {
		names = append(names, name)
		if count := len(strings.Fields(name)); count > maxTokens {
			maxTokens = count
		}
	}
	sort.Strings(names)

	var source strings.Builder
	source.WriteString("// Code generated by cmd/locality-gen; DO NOT EDIT.\n")
	source.WriteString("// Source: ")
	source.WriteString(endpoint)
	source.WriteString(" (ABS ASGS Edition 3, SAL 2021)\n\n")
	source.WriteString("package auaddress\n\n")
	fmt.Fprintf(&source, "const maxLocalityTokens = %d\n\n", maxTokens)
	source.WriteString("var localityStates = map[string]stateMask{\n")
	for _, name := range names {
		fmt.Fprintf(&source, "\t%q: 0b%08b,\n", name, localities[name])
	}
	source.WriteString("}\n")

	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated localities: %w", err)
	}
	return formatted, nil
}
